### ISSUE TITLE
Default spacing for lists is not standard?

### ISSUE THREAD

**Issue by niftylettuce** [wooorm/remark-preset-wooorm#13]
```md
* [Install](#install)
* [Features](#features)
* [Contributors](#contributors)
* [License](#license)
```

becomes this:

```md
*   [Install](#install)
*   [Features](#features)
*   [Contributors](#contributors)
*   [License](#license)
```

which afaik is not standard - can you fix this?

**Comment by niftylettuce** [comment]
it wasn't obvious I had to customize this at first <https://github.com/wooorm/remark/blob/86b049a0ca0e499c1aa06894c6bd7755c59dc9b9/packages/remark-stringify/lib/defaults.js>

to set `listItemIndent` in my package.json:

```json
  "remarkConfig": {
    "settings": {
      "listItemIndent": "1"
    },
```

**Comment by wooorm** [comment]
This is my personal style. Stuff doesn't have to be "standard" (in quotes because there is no standard for markdown) for it to be here.

Also: the reason for using a full "tab" is because otherwise you run into bugginess with different markdown flavours when combining lists with other nodes.

**Comment by niftylettuce** [comment]
make sense ty

**Comment by wooorm** [comment]
Finally, if you expected docs somewhere, feel free to open a PR to add them there, or references to other places!

**Comment by niftylettuce** [comment]
oh one more thing I had to do for anyone that comes to this issue was to add `[ "lint-list-item-indent", "space" ]` to `plugins`:

```
  "remarkConfig": {
    "settings": {
      "listItemIndent": "1"
    },
    "plugins": [
      [ "lint-list-item-indent", "space" ]
    ]
```
